name: docker-ci

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
  pull_request:
    paths:
      - 'docker/**'
  workflow_dispatch:
    inputs:
      app:
        description: 'docker/<app> to build'
        required: true
        type: string

permissions:
  contents: read
  packages: write
  id-token: write


concurrency:
  group: docker-ci-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  OWNER: ${{ github.repository_owner }}
  DOCKERHUB_ORG: cleot

jobs:
  detect:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      has_apps: ${{ steps.set-matrix.outputs.has_apps }}
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - id: set-matrix
        shell: bash
        run: |
          set -euo pipefail
          get_apps_from_diff() {
            local base
            if [ "${{ github.event_name }}" = "pull_request" ]; then
              base="${{ github.event.pull_request.base.sha }}"
            else
              base="HEAD~1"
            fi
            base=$(git merge-base "$base" HEAD)
            git diff --name-only "$base"...HEAD \
              | awk -F/ '/^docker\//{print $2}' \
              | awk 'NF' \
              | sort -u
          }
      
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            mapfile -t APPS < <(ls -1 docker 2>/dev/null || true)
          else
            mapfile -t APPS < <(get_apps_from_diff)
          fi
      
          # keep only dirs that have a Dockerfile
          FILTERED=()
          for d in "${APPS[@]}"; do
            [ -n "$d" ] && [ -f "docker/$d/Dockerfile" ] && FILTERED+=("$d")
          done
      
          if [ "${#FILTERED[@]}" -eq 0 ]; then
            echo 'matrix={"app":[]}' >> "$GITHUB_OUTPUT"
            echo 'has_apps=false' >> "$GITHUB_OUTPUT"
            exit 0
          fi
      
          # build JSON with jq
          printf '%s\0' "${FILTERED[@]}" \
            | jq -R -s 'split("\u0000")[:-1]' \
            | jq -c '{app: .}' \
            | { read -r MATRIX; echo "matrix=$MATRIX" >> "$GITHUB_OUTPUT"; }
      
          echo 'has_apps=true' >> "$GITHUB_OUTPUT"

  build:
    needs: detect
    if: ${{ needs.detect.outputs.has_apps == 'true' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4

      - name: Assert matrix.app not empty
        run: |
          test -n "${{ matrix.app }}" || { echo "empty matrix.app"; exit 1; }
          echo "Building app=${{ matrix.app }}"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ env.OWNER }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read VERSION (optional)
        id: version
        shell: bash
        run: |
          V=""
          [ -f "docker/${{ matrix.app }}/VERSION" ] && V=$(tr -d '\n' < "docker/${{ matrix.app }}/VERSION")
          echo "value=$V" >> "$GITHUB_OUTPUT"
      
      - name: docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.OWNER }}/${{ matrix.app }}
            docker.io/${{ env.DOCKERHUB_ORG }}/${{ matrix.app }}
          tags: |
            type=raw,value=sha-${{ github.sha }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=${{ steps.version.outputs.value }},enable=${{ github.ref == 'refs/heads/main' && steps.version.outputs.value != '' }}

      - name: build and push
        id: build_push
        uses: docker/build-push-action@v6
        with:
          context: ./docker/${{ matrix.app }}
          file: ./docker/${{ matrix.app }}/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha,scope=${{ matrix.app }}
          cache-to: type=gha,mode=max,scope=${{ matrix.app }}
          provenance: true
          platforms: linux/amd64,linux/arm64